import type { Surah } from './content';

/**
 * Complete, authentic directory of ALL 114 Surahs of the Holy Quran
 * with Arabic scripts, meanings, revelation classifications, and spiritual themes.
 */
export const all114Surahs: Surah[] = [
  {
    id: "1",
    number: 1,
    name: "Al-Fatihah",
    arabic: "الفاتحة",
    meaning: "The Opening",
    verses: 7,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 5,
    intro: {
      theme: "The Essence of the Quran and Prayer",
      verseCount: 7,
      overview: "Known as Umm al-Kitab (Mother of the Book), recited in every rakah of prayer, proclaiming praise, divine lordship, and the prayer for the straight path.",
      keyTakeaway: "Every beginning returns to mercy; worship and reliance upon Allah are the twin pillars of inner peace.",
    },
  },
  {
    id: "2",
    number: 2,
    name: "Al-Baqarah",
    arabic: "البقرة",
    meaning: "The Cow",
    verses: 286,
    time: "45 min",
    revelation: "Medinan",
    revelationOrder: 87,
    intro: {
      theme: "Covenant, Guidance, and Law",
      verseCount: 286,
      overview: "The longest chapter in the Quran, establishing the foundations of faith, divine legislation, civil conduct, family law, the story of Adam and the Israelites, and culminating in Ayat al-Kursi.",
      keyTakeaway: "Guidance is granted to those who guard against evil, believe in the unseen, establish prayer, and spend from their provision.",
    },
  },
  {
    id: "3",
    number: 3,
    name: "Ali 'Imran",
    arabic: "آل عمران",
    meaning: "Family of Imran",
    verses: 200,
    time: "45 min",
    revelation: "Medinan",
    revelationOrder: 89,
    intro: {
      theme: "Steadfastness of Faith and the Virgin Birth",
      verseCount: 200,
      overview: "Addresses the pure monotheistic lineage of Maryam, Zakariyya, and Isa, alongside the critical lessons of the Battle of Uhud, steadfastness, and unity.",
      keyTakeaway: "Do not lose heart nor grieve; you shall be victorious if you are true believers.",
    },
  },
  {
    id: "4",
    number: 4,
    name: "An-Nisa",
    arabic: "النساء",
    meaning: "The Women",
    verses: 176,
    time: "25 min",
    revelation: "Medinan",
    revelationOrder: 92,
    intro: {
      theme: "Social Justice, Family, and Protection of the Vulnerable",
      verseCount: 176,
      overview: "Establishes rights of orphans, women, inheritance, equitable justice, and civil ethics within the expanding Muslim society.",
      keyTakeaway: "Stand firmly for justice as witnesses to Allah, even if against yourselves, your parents, or kin.",
    },
  },
  {
    id: "5",
    number: 5,
    name: "Al-Ma'idah",
    arabic: "المائدة",
    meaning: "The Table Spread",
    verses: 120,
    time: "25 min",
    revelation: "Medinan",
    revelationOrder: 112,
    intro: {
      theme: "Fulfillment of Treaties and Finality of Religion",
      verseCount: 120,
      overview: "Revealed toward the close of the Prophetic mission, emphasizing covenant keeping, dietary purity, justice between faiths, and Isa's testimony on the Last Day.",
      keyTakeaway: "This day I have perfected for you your religion, completed My favor upon you, and chosen for you Islam.",
    },
  },
  {
    id: "6",
    number: 6,
    name: "Al-An'am",
    arabic: "الأنعام",
    meaning: "The Cattle",
    verses: 165,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 55,
    intro: {
      theme: "Tawhid and the Signs of Creation",
      verseCount: 165,
      overview: "A majestic proclamation of monotheism revealed all at once in Mecca, tracing Prophet Ibrahim's contemplation of celestial bodies.",
      keyTakeaway: "Say: Indeed, my prayer, my sacrifice, my living, and my dying are for Allah, Lord of the worlds.",
    },
  },
  {
    id: "7",
    number: 7,
    name: "Al-A'raf",
    arabic: "الأعراف",
    meaning: "The Heights",
    verses: 206,
    time: "45 min",
    revelation: "Meccan",
    revelationOrder: 39,
    intro: {
      theme: "The Struggle Between Good and Evil",
      verseCount: 206,
      overview: "Extensively chronicles the prophets Adam, Nuh, Hud, Saleh, Lut, Shu'ayb, and Musa facing Pharaoh, contrasting their humility with the arrogance of Iblis.",
      keyTakeaway: "Take to forgiveness, enjoin what is right, and turn away from the ignorant.",
    },
  },
  {
    id: "8",
    number: 8,
    name: "Al-Anfal",
    arabic: "الأنفال",
    meaning: "The Spoils of War",
    verses: 75,
    time: "12 min",
    revelation: "Medinan",
    revelationOrder: 88,
    intro: {
      theme: "Trust in Allah and the Victory of Badr",
      verseCount: 75,
      overview: "Revealed after the pivotal Battle of Badr, exploring spiritual preparedness, brotherhood, and the true meaning of divine assistance.",
      keyTakeaway: "The believers are only those who, when Allah is mentioned, their hearts feel fear, and when His verses are recited, their faith increases.",
    },
  },
  {
    id: "9",
    number: 9,
    name: "At-Tawbah",
    arabic: "التوبة",
    meaning: "The Repentance",
    verses: 129,
    time: "25 min",
    revelation: "Medinan",
    revelationOrder: 113,
    intro: {
      theme: "Sincerity, Hypocrisy, and Unconditional Mercy",
      verseCount: 129,
      overview: "Exposes hypocrisy during the expedition to Tabuk while detailing the boundless acceptance of sincere repentance for those who fall behind.",
      keyTakeaway: "If they turn away, say: Sufficient for me is Allah; there is no deity except Him. Upon Him I rely, and He is Lord of the Great Throne.",
    },
  },
  {
    id: "10",
    number: 10,
    name: "Yunus",
    arabic: "يونس",
    meaning: "Jonah",
    verses: 109,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 51,
    intro: {
      theme: "Divine Decree and Truth of Revelation",
      verseCount: 109,
      overview: "Reflects on the signs in the alternation of night and day, contrasting obstinate nations with the repentance of the people of Yunus.",
      keyTakeaway: "Say: In the bounty of Allah and in His mercy—in that let them rejoice; it is better than what they accumulate.",
    },
  },
  {
    id: "11",
    number: 11,
    name: "Hud",
    arabic: "هود",
    meaning: "Hud",
    verses: 123,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 52,
    intro: {
      theme: "Prophetic Perseverance and Steadfastness",
      verseCount: 123,
      overview: "Narrates the relentless determination of Nuh, Hud, Saleh, Ibrahim, Lut, and Shu'ayb. The Prophet ﷺ remarked: 'Surah Hud and its sisters made my hair turn gray.'",
      keyTakeaway: "Be steadfast as you have been commanded, and do not transgress.",
    },
  },
  {
    id: "12",
    number: 12,
    name: "Yusuf",
    arabic: "يوسف",
    meaning: "Joseph",
    verses: 111,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 53,
    intro: {
      theme: "The Best of Stories: Patience and Elevation",
      verseCount: 111,
      overview: "Revealed in the Year of Sorrow, following Yusuf from betrayal and prison to the seat of authority, proving that Allah is Sovereign over all affairs.",
      keyTakeaway: "He who fears Allah and is patient—indeed, Allah does not allow to be lost the reward of those who do good.",
    },
  },
  {
    id: "13",
    number: 13,
    name: "Ar-Ra'd",
    arabic: "الرعد",
    meaning: "The Thunder",
    verses: 43,
    time: "5 min",
    revelation: "Medinan",
    revelationOrder: 96,
    intro: {
      theme: "Cosmic Balance and Serenity of the Heart",
      verseCount: 43,
      overview: "The thunder glorifies His praise, and lightning awakens contemplation. Contrasts transient worldly illusions with lasting truth.",
      keyTakeaway: "Surely in the remembrance of Allah do hearts find rest.",
    },
  },
  {
    id: "14",
    number: 14,
    name: "Ibrahim",
    arabic: "إبراهيم",
    meaning: "Abraham",
    verses: 52,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 72,
    intro: {
      theme: "Gratitude and the Prayer of Abraham",
      verseCount: 52,
      overview: "Highlights the metaphor of the good word like a firm tree whose branches reach the heavens, featuring Prophet Ibrahim's tender prayer for his descendants in Mecca.",
      keyTakeaway: "If you are grateful, I will surely increase you in favor.",
    },
  },
  {
    id: "15",
    number: 15,
    name: "Al-Hijr",
    arabic: "الحجر",
    meaning: "The Rocky Tract",
    verses: 99,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 54,
    intro: {
      theme: "Divine Protection of the Remembrance",
      verseCount: 99,
      overview: "Addresses the stubbornness of the people of Thamud in Al-Hijr and gives comfort to the Prophet with the eternal promise of Quranic preservation.",
      keyTakeaway: "Indeed, it is We who sent down the Quran and indeed, We will be its guardian.",
    },
  },
  {
    id: "16",
    number: 16,
    name: "An-Nahl",
    arabic: "النحل",
    meaning: "The Bee",
    verses: 128,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 70,
    intro: {
      theme: "The Book of Blessings (Kitab an-Ni'am)",
      verseCount: 128,
      overview: "Celebrates the signs of Allah in nature: rainfall, cattle, honeybees, olive trees, and night garments, summoning humans to thankful worship.",
      keyTakeaway: "Invite to the way of your Lord with wisdom and good instruction, and argue with them in a way that is best.",
    },
  },
  {
    id: "17",
    number: 17,
    name: "Al-Isra",
    arabic: "الإسراء",
    meaning: "The Night Journey",
    verses: 111,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 50,
    intro: {
      theme: "Ascension, Moral Code, and Honoring Parents",
      verseCount: 111,
      overview: "Commemorates the miraculous journey from Mecca to Jerusalem and the ascension through the heavens, detailing a foundational 14-point moral charter.",
      keyTakeaway: "Your Lord has decreed that you worship none but Him, and that you be kind to parents.",
    },
  },
  {
    id: "18",
    number: 18,
    name: "Al-Kahf",
    arabic: "الكهف",
    meaning: "The Cave",
    verses: 110,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 69,
    intro: {
      theme: "Four Shields Against the Trials of Life",
      verseCount: 110,
      overview: "Recited every Friday, presenting 4 parables shielding against trials: the Youth of the Cave (trial of faith), the Two Gardens (trial of wealth), Musa and Khidr (trial of knowledge), and Dhul-Qarnayn (trial of power).",
      keyTakeaway: "Whoever hopes for the meeting with his Lord, let him do righteous work and not associate anyone in worship with his Lord.",
    },
  },
  {
    id: "19",
    number: 19,
    name: "Maryam",
    arabic: "مريم",
    meaning: "Mary",
    verses: 98,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 44,
    intro: {
      theme: "The Wonders of Divine Mercy (Rahman)",
      verseCount: 98,
      overview: "Rich with the divine name 'Ar-Rahman', recounting Zakariyya's prayer in old age, Maryam's solitary devotion and miraculous conception of Isa, and Ibrahim's gentle dawah.",
      keyTakeaway: "There is no one in the heavens and earth but that he comes to the Most Merciful as a servant.",
    },
  },
  {
    id: "20",
    number: 20,
    name: "Ta-Ha",
    arabic: "طه",
    meaning: "Ta-Ha",
    verses: 135,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 45,
    intro: {
      theme: "Comfort in Calling to Truth",
      verseCount: 135,
      overview: "Opens with reassuring words to Muhammad ﷺ: 'We have not sent down the Quran to cause you distress.' Contains the intimate dialogue of Musa at the burning bush.",
      keyTakeaway: "My Lord, expand for me my chest, and ease for me my task, and untie the knot from my tongue.",
    },
  },
  {
    id: "21",
    number: 21,
    name: "Al-Anbiya",
    arabic: "الأنبياء",
    meaning: "The Prophets",
    verses: 112,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 73,
    intro: {
      theme: "The Universal Chain of Prophetic Calling",
      verseCount: 112,
      overview: "Surveys 16 prophets including Ibrahim breaking the idols, Ayyub crying out in sickness, Yunus in the whale, and Maryam, uniting all in monotheism.",
      keyTakeaway: "We have not sent you, [O Muhammad], except as a mercy to the worlds.",
    },
  },
  {
    id: "22",
    number: 22,
    name: "Al-Hajj",
    arabic: "الحج",
    meaning: "The Pilgrimage",
    verses: 78,
    time: "12 min",
    revelation: "Medinan",
    revelationOrder: 103,
    intro: {
      theme: "The Assembly of Humanity and Sacred Rites",
      verseCount: 78,
      overview: "Reflects on the solemn tremor of the Day of Judgment and the global call to the Sacred House established by Ibrahim.",
      keyTakeaway: "Their meat will not reach Allah, nor will their blood, but what reaches Him is piety from you.",
    },
  },
  {
    id: "23",
    number: 23,
    name: "Al-Mu'minun",
    arabic: "المؤمنون",
    meaning: "The Believers",
    verses: 118,
    time: "25 min",
    revelation: "Meccan",
    revelationOrder: 74,
    intro: {
      theme: "Qualities of True Success",
      verseCount: 118,
      overview: "Opens by defining the seven characteristics of successful believers: humble prayer, avoiding vain talk, paying zakah, and guarding trust.",
      keyTakeaway: "Successful indeed are the believers: those who are humble in their prayers.",
    },
  },
  {
    id: "24",
    number: 24,
    name: "An-Nur",
    arabic: "النور",
    meaning: "The Light",
    verses: 64,
    time: "12 min",
    revelation: "Medinan",
    revelationOrder: 102,
    intro: {
      theme: "Purity, Social Modesty, and the Verse of Light",
      verseCount: 64,
      overview: "Guidelines for privacy, modest gaze, and communal dignity, featuring the famous Ayah an-Nur comparing Allah's light to a niche containing a radiant lamp.",
      keyTakeaway: "Allah is the Light of the heavens and the earth.",
    },
  },
  {
    id: "25",
    number: 25,
    name: "Al-Furqan",
    arabic: "الفرقان",
    meaning: "The Criterion",
    verses: 77,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 42,
    intro: {
      theme: "The Standard of Truth and the Servants of the Merciful",
      verseCount: 77,
      overview: "Contrasts skepticism with the grandeur of revelation, concluding with the beloved description of Ibad ar-Rahman (the Servants of the Most Merciful).",
      keyTakeaway: "The servants of the Most Merciful are those who walk upon the earth easily, and when the ignorant address them, they say peace.",
    },
  },
  {
    id: "26",
    number: 26,
    name: "Ash-Shu'ara",
    arabic: "الشعراء",
    meaning: "The Poets",
    verses: 227,
    time: "45 min",
    revelation: "Meccan",
    revelationOrder: 47,
    intro: {
      theme: "The Steadfast Voice of Truth",
      verseCount: 227,
      overview: "The longest surah in verse count after Al-Baqarah, repeating the prophetic refrain: 'Fear Allah and obey me; I ask of you no reward for it.'",
      keyTakeaway: "The Day when there will not benefit wealth or children, but only one who comes to Allah with a sound heart.",
    },
  },
  {
    id: "27",
    number: 27,
    name: "An-Naml",
    arabic: "النمل",
    meaning: "The Ant",
    verses: 93,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 48,
    intro: {
      theme: "Knowledge, Gratitude, and King Solomon",
      verseCount: 93,
      overview: "Highlights Sulayman hearing the warning of the tiny ant, his dialogue with the hoopoe bird, and the submission of the Queen of Sheba.",
      keyTakeaway: "My Lord, enable me to be grateful for Your favor which You have bestowed upon me and upon my parents.",
    },
  },
  {
    id: "28",
    number: 28,
    name: "Al-Qasas",
    arabic: "القصص",
    meaning: "The Stories",
    verses: 88,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 49,
    intro: {
      theme: "The Triumph of the Oppressed",
      verseCount: 88,
      overview: "Focuses deeply on Musa's infancy in the basket on the Nile, his sanctuary in Madyan, his confrontation with Pharaoh, and the downfall of wealthy Qarun.",
      keyTakeaway: "And We wished to confer favor upon those who were oppressed in the land and make them leaders.",
    },
  },
  {
    id: "29",
    number: 29,
    name: "Al-Ankabut",
    arabic: "العنكبوت",
    meaning: "The Spider",
    verses: 69,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 85,
    intro: {
      theme: "Tests of Sincerity and Fragile Falsehood",
      verseCount: 69,
      overview: "Addresses believers facing persecution in Mecca, using the metaphor of the spider's fragile web to expose the weakness of relying on anything other than Allah.",
      keyTakeaway: "Do the people think that they will be left to say 'We believe' and they will not be tested?",
    },
  },
  {
    id: "30",
    number: 30,
    name: "Ar-Rum",
    arabic: "الروم",
    meaning: "The Romans",
    verses: 60,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 84,
    intro: {
      theme: "Prophecy and Signs in the Horizon",
      verseCount: 60,
      overview: "Accurately foretold the reversal of fortunes between Byzantine and Persian empires, and highlights signs in marital affection and the diversity of languages.",
      keyTakeaway: "And of His signs is that He created for you from yourselves mates that you may find tranquility in them.",
    },
  },
  {
    id: "31",
    number: 31,
    name: "Luqman",
    arabic: "لقمان",
    meaning: "Luqman",
    verses: 34,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 57,
    intro: {
      theme: "Wisdom, Parenting, and Humility",
      verseCount: 34,
      overview: "Preserves the timeless counsel of the sage Luqman to his son: shun idolatry, honor mother and father, establish prayer, and walk with modesty.",
      keyTakeaway: "Do not turn your cheek in contempt toward people and do not walk through the earth exultantly.",
    },
  },
  {
    id: "32",
    number: 32,
    name: "As-Sajdah",
    arabic: "السجدة",
    meaning: "The Prostration",
    verses: 30,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 75,
    intro: {
      theme: "Creation, Revelation, and Night Worship",
      verseCount: 30,
      overview: "The Prophet ﷺ would recite this every Friday dawn prayer. Portrays those whose sides forsake their beds to call upon their Lord in fear and hope.",
      keyTakeaway: "No soul knows what has been hidden for them of comfort for eyes as reward for what they used to do.",
    },
  },
  {
    id: "33",
    number: 33,
    name: "Al-Ahzab",
    arabic: "الأحزاب",
    meaning: "The Confederates",
    verses: 73,
    time: "12 min",
    revelation: "Medinan",
    revelationOrder: 90,
    intro: {
      theme: "Trials of Siege and the Prophetic Character",
      verseCount: 73,
      overview: "Chronicles the harrowing Battle of the Trench when allied armies encircled Medina, highlighting unwavering faith under extreme pressure.",
      keyTakeaway: "There has certainly been for you in the Messenger of Allah an excellent pattern for whoever hopes in Allah and the Last Day.",
    },
  },
  {
    id: "34",
    number: 34,
    name: "Saba",
    arabic: "سبأ",
    meaning: "Sheba",
    verses: 54,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 58,
    intro: {
      theme: "Gratitude versus Arrogant Ingratitude",
      verseCount: 54,
      overview: "Contrasts the thankful kingdoms of Dawud and Sulayman with the ungrateful people of Sheba whose bountiful gardens were washed away by a devastating flood.",
      keyTakeaway: "Work, O family of David, in gratitude. And few of My servants are grateful.",
    },
  },
  {
    id: "35",
    number: 35,
    name: "Fatir",
    arabic: "فاطر",
    meaning: "The Originator",
    verses: 45,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 43,
    intro: {
      theme: "The Originator of the Heavens and Angels",
      verseCount: 45,
      overview: "Celebrates the Creator who appointed angels with wings, and reminds humans of their absolute dependence on Allah while He is Free of need.",
      keyTakeaway: "O mankind, you are those in need of Allah, while Allah is the Free of need, the Praiseworthy.",
    },
  },
  {
    id: "36",
    number: 36,
    name: "Ya-Sin",
    arabic: "يس",
    meaning: "Ya-Sin",
    verses: 83,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 41,
    intro: {
      theme: "The Heart of the Quran: Signs, Parables, Resurrection",
      verseCount: 83,
      overview: "Celebrated as the heart of the Quran, exploring the authenticity of the message, parables of the town that rejected messengers, signs in nature, and resurrection.",
      keyTakeaway: "His command is only when He intends a thing that He says to it, 'Be,' and it is.",
    },
  },
  {
    id: "37",
    number: 37,
    name: "As-Saffat",
    arabic: "الصافات",
    meaning: "Those Who Set The Ranks",
    verses: 182,
    time: "45 min",
    revelation: "Meccan",
    revelationOrder: 56,
    intro: {
      theme: "Celestial Ranks and the Great Sacrifice",
      verseCount: 182,
      overview: "Opens with angels lined up in ranks, and narrates Prophet Ibrahim's supreme trial of willingness to sacrifice his beloved son in submission to Allah.",
      keyTakeaway: "Peace be upon Noah among the worlds. Indeed, We thus reward the doers of good.",
    },
  },
  {
    id: "38",
    number: 38,
    name: "Sad",
    arabic: "ص",
    meaning: "Sad",
    verses: 88,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 38,
    intro: {
      theme: "Patience of Dawud, Sulayman, and Ayyub",
      verseCount: 88,
      overview: "Addresses the stubbornness of Quraysh opponents, countering with the devotion and repenting hearts of King David, Solomon, and Job.",
      keyTakeaway: "A blessed Book which We have revealed to you, [O Muhammad], that they might reflect upon its verses.",
    },
  },
  {
    id: "39",
    number: 39,
    name: "Az-Zumar",
    arabic: "الزمر",
    meaning: "The Groups",
    verses: 75,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 59,
    intro: {
      theme: "Pure Devotion and the Gate of Hope",
      verseCount: 75,
      overview: "Urges unadulterated monotheism, depicting groups led to Paradise or Hell, and containing the most hopeful verse of forgiveness in the Quran.",
      keyTakeaway: "Say: O My servants who have transgressed against themselves, do not despair of the mercy of Allah. Indeed, Allah forgives all sins.",
    },
  },
  {
    id: "40",
    number: 40,
    name: "Ghafir",
    arabic: "غافر",
    meaning: "The Forgiver",
    verses: 85,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 60,
    intro: {
      theme: "Divine Forgiveness and the Believer of Pharaoh's Family",
      verseCount: 85,
      overview: "The first of the seven Ha-Meem surahs, praising Allah as Forgiver of sin and Acceptor of repentance, highlighting the secret believer who stood for Musa.",
      keyTakeaway: "Your Lord says: Call upon Me; I will respond to you.",
    },
  },
  {
    id: "41",
    number: 41,
    name: "Fussilat",
    arabic: "فصلت",
    meaning: "Explained in Detail",
    verses: 54,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 61,
    intro: {
      theme: "Signs in the Horizon and Within Ourselves",
      verseCount: 54,
      overview: "Details the stages of cosmic creation, urging believers to repel evil with what is better, turning enmity into close friendship.",
      keyTakeaway: "We will show them Our signs in the horizons and within themselves until it becomes clear to them that it is the truth.",
    },
  },
  {
    id: "42",
    number: 42,
    name: "Ash-Shura",
    arabic: "الشورى",
    meaning: "The Consultation",
    verses: 53,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 62,
    intro: {
      theme: "Unity of Divine Revelation and Mutual Counsel",
      verseCount: 53,
      overview: "Emphasizes the unified message given to Nuh, Ibrahim, Musa, Isa, and Muhammad, commanding community affairs to be decided by mutual consultation.",
      keyTakeaway: "There is nothing like unto Him, and He is the Hearing, the Seeing.",
    },
  },
  {
    id: "43",
    number: 43,
    name: "Az-Zukhruf",
    arabic: "الزخرف",
    meaning: "The Ornaments of Gold",
    verses: 89,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 63,
    intro: {
      theme: "Real Worth versus Worldly Glitz",
      verseCount: 89,
      overview: "Demonstrates that gold, silver, and earthly ornaments are temporary provisions, whereas the honor of the hereafter belongs to the mindful.",
      keyTakeaway: "And whoever is blinded from remembrance of the Most Merciful—We appoint for him a devil.",
    },
  },
  {
    id: "44",
    number: 44,
    name: "Ad-Dukhan",
    arabic: "الدخان",
    meaning: "The Smoke",
    verses: 59,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 64,
    intro: {
      theme: "The Blessed Night and Warning Signs",
      verseCount: 59,
      overview: "Revealed concerning the Blessed Night of Decree in which every matter of wisdom is distinctly explained, recounting the warning smoke.",
      keyTakeaway: "Indeed, We sent it down during a blessed night.",
    },
  },
  {
    id: "45",
    number: 45,
    name: "Al-Jathiyah",
    arabic: "الجاثية",
    meaning: "The Crouching",
    verses: 37,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 65,
    intro: {
      theme: "The Kneeling Assembly of Nations",
      verseCount: 37,
      overview: "Presents countless signs in the heavens and earth, concluding with the awe-inspiring vision of every nation kneeling before its record of deeds.",
      keyTakeaway: "To Allah belongs all praise, Lord of the heavens and Lord of the earth, Lord of the worlds.",
    },
  },
  {
    id: "46",
    number: 46,
    name: "Al-Ahqaf",
    arabic: "الأحقاف",
    meaning: "The Sand Dunes",
    verses: 35,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 66,
    intro: {
      theme: "Filial Piety and the Fate of 'Ad",
      verseCount: 35,
      overview: "The last of the Ha-Meem surahs, enjoining kindness to mothers during gestation and nursing, and recording the jinn who listened to the Quran.",
      keyTakeaway: "And We have enjoined upon man, to his parents, good treatment.",
    },
  },
  {
    id: "47",
    number: 47,
    name: "Muhammad",
    arabic: "محمد",
    meaning: "Muhammad",
    verses: 38,
    time: "5 min",
    revelation: "Medinan",
    revelationOrder: 95,
    intro: {
      theme: "Truth versus Falsehood and Mending of Condition",
      verseCount: 38,
      overview: "Contrasts the spiritual state of believers with that of disbelievers, promising that Allah will expiate the sins of believers and mend their condition.",
      keyTakeaway: "Those who believe and do righteous deeds... He will remove from them their misdeeds and amend their condition.",
    },
  },
  {
    id: "48",
    number: 48,
    name: "Al-Fath",
    arabic: "الفتح",
    meaning: "The Clear Victory",
    verses: 29,
    time: "5 min",
    revelation: "Medinan",
    revelationOrder: 111,
    intro: {
      theme: "The Treaty of Hudaybiyyah and Inner Peace",
      verseCount: 29,
      overview: "Celebrates the apparent setback of the Treaty of Hudaybiyyah as a manifest spiritual and strategic triumph that paved the way for peace.",
      keyTakeaway: "It is He who sent down tranquility into the hearts of the believers that they would increase in faith.",
    },
  },
  {
    id: "49",
    number: 49,
    name: "Al-Hujurat",
    arabic: "الحجرات",
    meaning: "The Private Chambers",
    verses: 18,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 106,
    intro: {
      theme: "Social Ethics and Human Brotherhood",
      verseCount: 18,
      overview: "A masterpiece of social ethics forbidding mockery, spying, backbiting, and racial superiority, declaring that the most noble is the most righteous.",
      keyTakeaway: "Indeed, the most noble of you in the sight of Allah is the most righteous of you.",
    },
  },
  {
    id: "50",
    number: 50,
    name: "Qaf",
    arabic: "ق",
    meaning: "Qaf",
    verses: 45,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 34,
    intro: {
      theme: "The Creation, Death, and Nearness of Allah",
      verseCount: 45,
      overview: "A gripping sermon often recited by the Prophet ﷺ during Friday khutbah, illustrating how rain revives dead earth just as souls are resurrected.",
      keyTakeaway: "And We are closer to him than his jugular vein.",
    },
  },
  {
    id: "51",
    number: 51,
    name: "Adh-Dhariyat",
    arabic: "الذاريات",
    meaning: "The Winnowing Winds",
    verses: 60,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 67,
    intro: {
      theme: "The Purpose of Creation",
      verseCount: 60,
      overview: "Takes oaths by the scattering winds and rain-bearing clouds, culminating in the foundational statement of human and jinn existence.",
      keyTakeaway: "And I did not create the jinn and mankind except to worship Me.",
    },
  },
  {
    id: "52",
    number: 52,
    name: "At-Tur",
    arabic: "الطور",
    meaning: "The Mount",
    verses: 49,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 76,
    intro: {
      theme: "The Sacred Mount and Heavenly Bliss",
      verseCount: 49,
      overview: "Swears by Mount Sinai and the Inhabited House in heaven, depicting families reunited in Paradise with overflowing cups of joy.",
      keyTakeaway: "So be patient for the decision of your Lord, for indeed, you are in Our eyes.",
    },
  },
  {
    id: "53",
    number: 53,
    name: "An-Najm",
    arabic: "النجم",
    meaning: "The Star",
    verses: 62,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 23,
    intro: {
      theme: "The Vision of the Prophet at the Lote Tree",
      verseCount: 62,
      overview: "The first surah recited publicly by the Prophet ﷺ at the Ka'bah, describing his vision of Angel Jibril at Sidrat al-Muntaha during the Ascension.",
      keyTakeaway: "And that to your Lord is the final destination.",
    },
  },
  {
    id: "54",
    number: 54,
    name: "Al-Qamar",
    arabic: "القمر",
    meaning: "The Moon",
    verses: 55,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 37,
    intro: {
      theme: "The Splitting of the Moon and Ease of Remembrance",
      verseCount: 55,
      overview: "Opens with the miraculous splitting of the moon, repeating four times like a rhythmic chorus: 'And We have certainly made the Quran easy for remembrance.'",
      keyTakeaway: "And We have certainly made the Quran easy for remembrance, so is there any who will remember?",
    },
  },
  {
    id: "55",
    number: 55,
    name: "Ar-Rahman",
    arabic: "الرحمن",
    meaning: "The Most Merciful",
    verses: 78,
    time: "12 min",
    revelation: "Medinan",
    revelationOrder: 97,
    intro: {
      theme: "The Beauty of Creation and the Repeated Refrain",
      verseCount: 78,
      overview: "Known as the Bride of the Quran ('Arus al-Qur'an), repeating 31 times: 'Which of the favors of your Lord will you deny?' through cosmic harmony and Paradise.",
      keyTakeaway: "Which of the favors of your Lord will you deny?",
    },
  },
  {
    id: "56",
    number: 56,
    name: "Al-Waqi'ah",
    arabic: "الواقعة",
    meaning: "The Inevitable",
    verses: 96,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 46,
    intro: {
      theme: "The Three Categories of Humanity on the Last Day",
      verseCount: 96,
      overview: "Divided into the Foremost (As-Sabiqun), the Companions of the Right, and the Companions of the Left, recited nightly as a safeguard against spiritual poverty.",
      keyTakeaway: "Then glorify the name of your Lord, the Most Great.",
    },
  },
  {
    id: "57",
    number: 57,
    name: "Al-Hadid",
    arabic: "الحديد",
    meaning: "The Iron",
    verses: 29,
    time: "5 min",
    revelation: "Medinan",
    revelationOrder: 94,
    intro: {
      theme: "Inner Light and the Sending Down of Iron",
      verseCount: 29,
      overview: "Balances spiritual humility with tangible strength, mentioning iron sent down with mighty power for human benefit.",
      keyTakeaway: "Has the time not come for those who have believed that their hearts should become humbly submissive at the remembrance of Allah?",
    },
  },
  {
    id: "58",
    number: 58,
    name: "Al-Mujadila",
    arabic: "المجادلة",
    meaning: "The Pleading Woman",
    verses: 22,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 105,
    intro: {
      theme: "The Secret Conversation and Social Justice",
      verseCount: 22,
      overview: "Every single verse in this surah contains the name 'Allah', opening with Allah hearing the quiet plea of a wronged woman in her home.",
      keyTakeaway: "There is no private conversation three but that He is their fourth... He is with them wherever they are.",
    },
  },
  {
    id: "59",
    number: 59,
    name: "Al-Hashr",
    arabic: "الحشر",
    meaning: "The Gathering / Exile",
    verses: 24,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 101,
    intro: {
      theme: "Divine Transcendence and the Most Beautiful Names",
      verseCount: 24,
      overview: "Concludes with the profound passage describing what would happen if the Quran were revealed onto a mountain, followed by the majestic Names of Allah.",
      keyTakeaway: "He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Bestower of Faith.",
    },
  },
  {
    id: "60",
    number: 60,
    name: "Al-Mumtahanah",
    arabic: "الممتحنة",
    meaning: "She That Is Examined",
    verses: 13,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 91,
    intro: {
      theme: "Examining Loyalties and Peaceful Relations",
      verseCount: 13,
      overview: "Distinguishes between peaceful non-Muslims who should be treated with kindness and equity, and belligerent oppressors who drive people from their homes.",
      keyTakeaway: "Allah does not forbid you from those who do not fight you because of religion... to deal kindly and justly with them.",
    },
  },
  {
    id: "61",
    number: 61,
    name: "As-Saff",
    arabic: "الصف",
    meaning: "The Battle Array",
    verses: 14,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 109,
    intro: {
      theme: "Matching Words with Actions",
      verseCount: 14,
      overview: "Reproaches claiming commitment without delivering action, calling believers to align intentions, deeds, and mutual solidarity.",
      keyTakeaway: "O you who have believed, why do you say what you do not do? Great is hatred in the sight of Allah that you say what you do not do.",
    },
  },
  {
    id: "62",
    number: 62,
    name: "Al-Jumu'ah",
    arabic: "الجمعة",
    meaning: "Friday Congregation",
    verses: 11,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 110,
    intro: {
      theme: "The Call to Friday Prayer and Remembrance",
      verseCount: 11,
      overview: "Addresses the purification of souls through revelation, commanding believers to leave trade and race to the remembrance of Allah when the call is made.",
      keyTakeaway: "When the call is proclaimed for the prayer on the day of [Jumu'ah], proceed to the remembrance of Allah and leave trade.",
    },
  },
  {
    id: "63",
    number: 63,
    name: "Al-Munafiqun",
    arabic: "المنافقون",
    meaning: "The Hypocrites",
    verses: 11,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 104,
    intro: {
      theme: "Unmasking Hypocrisy and Preparing for Death",
      verseCount: 11,
      overview: "Exposes duplicity in speech and warns believers not to allow wealth or children to distract them from the remembrance of Allah.",
      keyTakeaway: "And spend [in the way of Allah] from what We have provided you before death approaches one of you.",
    },
  },
  {
    id: "64",
    number: 64,
    name: "At-Taghabun",
    arabic: "التغابن",
    meaning: "Mutual Disillusion",
    verses: 18,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 108,
    intro: {
      theme: "The Day of Mutual Gain and Loss",
      verseCount: 18,
      overview: "Presents the Day of Judgment as a day where true spiritual profit and worldly illusion are laid bare, enjoining trust and forgiveness in family life.",
      keyTakeaway: "So fear Allah as much as you are able and listen and obey and spend; that is better for your souls.",
    },
  },
  {
    id: "65",
    number: 65,
    name: "At-Talaq",
    arabic: "الطلاق",
    meaning: "The Divorce",
    verses: 12,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 99,
    intro: {
      theme: "Dignity in Parting and Divine Provision",
      verseCount: 12,
      overview: "Often called Surah an-Nisa as-Sughra, embedding the highest spiritual promises of relief and provision within times of marital rupture.",
      keyTakeaway: "And whoever fears Allah—He will make for him a way out and provide for him from where he does not expect.",
    },
  },
  {
    id: "66",
    number: 66,
    name: "At-Tahrim",
    arabic: "التحريم",
    meaning: "The Prohibition",
    verses: 12,
    time: "2 min",
    revelation: "Medinan",
    revelationOrder: 107,
    intro: {
      theme: "Domestic Harmony and Spiritual Independence",
      verseCount: 12,
      overview: "Offers four parables of women: the wives of Nuh and Lut who chose disbelief, and Asiya (wife of Pharaoh) and Maryam who achieved spiritual perfection.",
      keyTakeaway: "O you who have believed, protect yourselves and your families from a Fire.",
    },
  },
  {
    id: "67",
    number: 67,
    name: "Al-Mulk",
    arabic: "الملك",
    meaning: "The Sovereignty",
    verses: 30,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 77,
    intro: {
      theme: "The Flawless Universe and Protection in the Grave",
      verseCount: 30,
      overview: "Recited nightly as an intercessor in the grave, urging contemplation of the seven heavens created in complete harmony without defect.",
      keyTakeaway: "He who created death and life to test you as to which of you is best in deed.",
    },
  },
  {
    id: "68",
    number: 68,
    name: "Al-Qalam",
    arabic: "القلم",
    meaning: "The Pen",
    verses: 52,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 2,
    intro: {
      theme: "The Pen, Noble Character, and the Ruined Garden",
      verseCount: 52,
      overview: "The second revelation, defending the Prophet's sanity and testifying to his sublime moral character, followed by the parable of the selfish garden owners.",
      keyTakeaway: "And indeed, you are of a great moral character.",
    },
  },
  {
    id: "69",
    number: 69,
    name: "Al-Haqqah",
    arabic: "الحاقة",
    meaning: "The Inevitable Reality",
    verses: 52,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 78,
    intro: {
      theme: "The Indisputable Day of Reckoning",
      verseCount: 52,
      overview: "Vividly depicts the blowing of the Horn, the earth ground to powder, and people receiving their books in their right or left hands.",
      keyTakeaway: "So as for he who is given his record in his right hand, he will say, 'Here, read my record!'",
    },
  },
  {
    id: "70",
    number: 70,
    name: "Al-Ma'arij",
    arabic: "المعارج",
    meaning: "The Ascending Stairways",
    verses: 44,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 79,
    intro: {
      theme: "Human Restlessness and Consistent Prayer",
      verseCount: 44,
      overview: "Analyzes human psychological fragility—anxious when touched by evil and withholding when touched by good—except those steadfast in prayer.",
      keyTakeaway: "Indeed, mankind was created anxious: when evil touches him, impatient, and when good touches him, withholding—except the observers of prayer.",
    },
  },
  {
    id: "71",
    number: 71,
    name: "Nuh",
    arabic: "نوح",
    meaning: "Noah",
    verses: 28,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 71,
    intro: {
      theme: "A Prophet's Heartbreaking 950-Year Dawah",
      verseCount: 28,
      overview: "Dedicated entirely to Prophet Nuh calling his people night and day, publicly and privately, explaining the blessings of seeking forgiveness.",
      keyTakeaway: "I said: Ask forgiveness of your Lord. Indeed, He is ever a Perpetual Forgiver. He will send [rain from] the sky upon you in showers.",
    },
  },
  {
    id: "72",
    number: 72,
    name: "Al-Jinn",
    arabic: "الجن",
    meaning: "The Jinn",
    verses: 28,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 40,
    intro: {
      theme: "The Unseen Realm Listening to Revelation",
      verseCount: 28,
      overview: "Documents a group of jinn hearing the Quran recited by the Prophet ﷺ in Nakhlah, immediately recognizing its beauty and submitting to monotheism.",
      keyTakeaway: "Say, [O Muhammad], 'It has been revealed to me that a group of the jinn listened and said, Indeed, we have heard an amazing Quran.'",
    },
  },
  {
    id: "73",
    number: 73,
    name: "Al-Muzzammil",
    arabic: "المزمل",
    meaning: "The Enfolded One",
    verses: 20,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 3,
    intro: {
      theme: "Night Vigil (Qiyam al-Layl) and Measured Recitation",
      verseCount: 20,
      overview: "Commands the Prophet to stand in the quiet stillness of the night, reciting the Quran with slow, rhythmic chant (Tartil) to carry a weighty word.",
      keyTakeaway: "Stand [to pray] through the night, except for a little... and recite the Quran with measured rhythmic recitation.",
    },
  },
  {
    id: "74",
    number: 74,
    name: "Al-Muddaththir",
    arabic: "المدثر",
    meaning: "The Cloaked One",
    verses: 56,
    time: "12 min",
    revelation: "Meccan",
    revelationOrder: 4,
    intro: {
      theme: "The Call to Arise and Warn",
      verseCount: 56,
      overview: "Marks the active launch of public prophetic mission: rise, warn, magnify your Lord, purify your garments, and abandon all impurities.",
      keyTakeaway: "O you who covers himself, arise and warn! And your Lord glorify, and your clothing purify.",
    },
  },
  {
    id: "75",
    number: 75,
    name: "Al-Qiyamah",
    arabic: "القيامة",
    meaning: "The Resurrection",
    verses: 40,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 31,
    intro: {
      theme: "The Self-Accusing Soul and Radiant Faces",
      verseCount: 40,
      overview: "Swears by the Day of Resurrection and the conscience (an-Nafs al-Lawwamah), affirming that Allah can reconstruct even individual fingertips.",
      keyTakeaway: "Some faces, that Day, will be radiant, looking at their Lord.",
    },
  },
  {
    id: "76",
    number: 76,
    name: "Al-Insan",
    arabic: "الإنسان",
    meaning: "Human / Time",
    verses: 31,
    time: "5 min",
    revelation: "Medinan",
    revelationOrder: 98,
    intro: {
      theme: "Selfless Charity and Heavenly Spring",
      verseCount: 31,
      overview: "Celebrates the righteous who feed the poor, orphan, and captive purely for the love of Allah, asking for neither reward nor gratitude.",
      keyTakeaway: "We feed you only for the countenance of Allah. We wish not from you reward or gratitude.",
    },
  },
  {
    id: "77",
    number: 77,
    name: "Al-Mursalat",
    arabic: "المرسلات",
    meaning: "The Winds Sent Forth",
    verses: 50,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 33,
    intro: {
      theme: "The Cosmic Winds and the Day of Decision",
      verseCount: 50,
      overview: "Opens with winds sent forth in swift succession, repeating the sobering refrain: 'Woe that Day to the deniers.'",
      keyTakeaway: "Indeed, the righteous will be among shades and springs.",
    },
  },
  {
    id: "78",
    number: 78,
    name: "An-Naba",
    arabic: "النبأ",
    meaning: "The Great News",
    verses: 40,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 80,
    intro: {
      theme: "The Great News of Resurrection",
      verseCount: 40,
      overview: "The opening of Juz 30 (Juz 'Amma), questioning the great news they dispute and pointing to mountains as pegs and sleep as rest.",
      keyTakeaway: "Indeed, for the righteous is attainment: gardens and grapevines.",
    },
  },
  {
    id: "79",
    number: 79,
    name: "An-Nazi'at",
    arabic: "النازعات",
    meaning: "Those Who Pull Out",
    verses: 46,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 81,
    intro: {
      theme: "The Stripping of the Soul and Pharaoh's Fall",
      verseCount: 46,
      overview: "Contrasts the forceful pulling out of wicked souls with the gentle drawing of pure souls, recounting Musa's warning to Pharaoh.",
      keyTakeaway: "As for he who transgressed and preferred the life of the world, Hell will be his refuge.",
    },
  },
  {
    id: "80",
    number: 80,
    name: "'Abasa",
    arabic: "عبس",
    meaning: "He Frowned",
    verses: 42,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 24,
    intro: {
      theme: "Divine Correction and the Blind Seeker",
      verseCount: 42,
      overview: "A tender yet firm divine reprimand to the Prophet ﷺ for turning away from the sincere blind companion Ibn Umm Maktum to address chieftains.",
      keyTakeaway: "But as for he who came to you striving while he feared Allah—from him you were distracted.",
    },
  },
  {
    id: "81",
    number: 81,
    name: "At-Takwir",
    arabic: "التكوير",
    meaning: "The Overthrowing",
    verses: 29,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 7,
    intro: {
      theme: "Cosmic Unfolding and the Soul's Record",
      verseCount: 29,
      overview: "When the sun is folded up, stars fall, oceans boil, and the infant girl buried alive is asked for what sin she was slain.",
      keyTakeaway: "When the sky is unveiled, a soul will know what it has brought.",
    },
  },
  {
    id: "82",
    number: 82,
    name: "Al-Infitar",
    arabic: "الانفطار",
    meaning: "The Cleaving Asunder",
    verses: 19,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 82,
    intro: {
      theme: "The Loving Kindness of the Lord We Forget",
      verseCount: 19,
      overview: "Pleads with humanity: 'O mankind, what has deceived you concerning your generous Lord who created you and proportioned you?'",
      keyTakeaway: "O mankind, what has deceived you concerning your Lord, the Generous?",
    },
  },
  {
    id: "83",
    number: 83,
    name: "Al-Mutaffifin",
    arabic: "المطففين",
    meaning: "Those Who Defraud",
    verses: 36,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 86,
    intro: {
      theme: "Commercial Integrity and the Sealed Records",
      verseCount: 36,
      overview: "Warns merchants who demand full measure when buying but cheat when selling, contrasting the low dungeon (Sijjin) with heights (Illiyyun).",
      keyTakeaway: "Woe to those who give less than due, who, when they take a measure from people, take in full.",
    },
  },
  {
    id: "84",
    number: 84,
    name: "Al-Inshiqaq",
    arabic: "الانشقاق",
    meaning: "The Splitting Asunder",
    verses: 25,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 83,
    intro: {
      theme: "Laboring Toward Your Lord and the Easy Reckoning",
      verseCount: 25,
      overview: "The sky listens to its Lord and is duty-bound, comforting the seeker that whoever receives their book in their right hand will have an easy reckoning.",
      keyTakeaway: "O mankind, indeed you are laboring toward your Lord with [great] exertion and will meet Him.",
    },
  },
  {
    id: "85",
    number: 85,
    name: "Al-Buruj",
    arabic: "البروج",
    meaning: "The Constellations",
    verses: 22,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 27,
    intro: {
      theme: "Martyrs of the Ditch and the Preserved Tablet",
      verseCount: 22,
      overview: "Recounts the young boy and the faithful burned in the trench of fire, assuring that Allah's retribution is severe while His mercy is absolute.",
      keyTakeaway: "Indeed, those who have believed and done righteous deeds will have gardens beneath which rivers flow.",
    },
  },
  {
    id: "86",
    number: 86,
    name: "At-Tariq",
    arabic: "الطارق",
    meaning: "The Night-Comer",
    verses: 17,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 36,
    intro: {
      theme: "The Piercing Star and the Watchful Guardian",
      verseCount: 17,
      overview: "Takes oath by the piercing night star that every single soul has a watchful angel appointed over it, observing human origins from fluid.",
      keyTakeaway: "There is no soul but that it has over it a protector.",
    },
  },
  {
    id: "87",
    number: 87,
    name: "Al-A'la",
    arabic: "الأعلى",
    meaning: "The Most High",
    verses: 19,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 8,
    intro: {
      theme: "Glorifying the Most High and the Eternal Garden",
      verseCount: 19,
      overview: "Beloved by the Prophet for Eid and Jumu'ah prayers: praise the Lord who created, proportioned, and decreed guidance.",
      keyTakeaway: "He has certainly succeeded who purifies himself and mentions the name of his Lord and prays.",
    },
  },
  {
    id: "88",
    number: 88,
    name: "Al-Ghashiyah",
    arabic: "الغاشية",
    meaning: "The Overwhelming Event",
    verses: 26,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 68,
    intro: {
      theme: "Contemplating the Camel, Sky, Mountains, and Earth",
      verseCount: 26,
      overview: "Contrasts exhausted faces in fire with joyful faces in gardens, summoning human reason to look at how camels were formed and mountains rooted.",
      keyTakeaway: "Then do they not look at the camels—how they are created? And at the sky—how it is raised?",
    },
  },
  {
    id: "89",
    number: 89,
    name: "Al-Fajr",
    arabic: "الفجر",
    meaning: "The Dawn",
    verses: 30,
    time: "5 min",
    revelation: "Meccan",
    revelationOrder: 10,
    intro: {
      theme: "The Ten Sacred Nights and the Soul at Rest",
      verseCount: 30,
      overview: "Swears by the dawn and the ten sacred nights of Dhul-Hijjah, concluding with the sweetest invitation to the tranquil soul (an-Nafs al-Mutma'innah).",
      keyTakeaway: "O tranquil soul, return to your Lord, well-pleased and pleasing [to Him], and enter among My righteous servants.",
    },
  },
  {
    id: "90",
    number: 90,
    name: "Al-Balad",
    arabic: "البلد",
    meaning: "The City",
    verses: 20,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 35,
    intro: {
      theme: "The Uphill Climb of Compassion",
      verseCount: 20,
      overview: "Swears by the sacred city of Mecca, affirming that humans were created for toil, challenging them to scale the uphill path of freeing captives and feeding orphans.",
      keyTakeaway: "And what can make you know what is [breaking through] the difficult pass? It is the freeing of a slave or feeding on a day of severe hunger an orphan of near relationship.",
    },
  },
  {
    id: "91",
    number: 91,
    name: "Ash-Shams",
    arabic: "الشمس",
    meaning: "The Sun",
    verses: 15,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 26,
    intro: {
      theme: "The Eleven Oaths and Purification of the Soul",
      verseCount: 15,
      overview: "The longest sequence of consecutive oaths in the Quran (11 oaths by the sun, moon, day, night, sky, earth, and soul), pivoting on self-purification.",
      keyTakeaway: "He has succeeded who purifies it, and he has failed who instills it [with corruption].",
    },
  },
  {
    id: "92",
    number: 92,
    name: "Al-Layl",
    arabic: "الليل",
    meaning: "The Night",
    verses: 21,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 9,
    intro: {
      theme: "Generous Giving and the Path to Ease",
      verseCount: 21,
      overview: "Contrasts two life paths: the one who gives in charity, fears Allah, and believes in the best reward—He will ease him toward ultimate ease.",
      keyTakeaway: "As for he who gives and fears Allah and believes in the best [reward], We will ease him toward ease.",
    },
  },
  {
    id: "93",
    number: 93,
    name: "Ad-Duha",
    arabic: "الضحى",
    meaning: "The Morning Brightness",
    verses: 11,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 11,
    intro: {
      theme: "Healing After Silence and Despair",
      verseCount: 11,
      overview: "Revealed when revelation paused and critics mocked that Allah had abandoned Muhammad: swearing by the bright morning and dark night that your Lord has neither left nor detested you.",
      keyTakeaway: "Your Lord has not taken leave of you, [O Muhammad], nor has He detested. And the Hereafter is better for you than the first [life].",
    },
  },
  {
    id: "94",
    number: 94,
    name: "Ash-Sharh",
    arabic: "الشرح",
    meaning: "The Expansion of the Breast",
    verses: 8,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 12,
    intro: {
      theme: "Easing the Heavy Burden",
      verseCount: 8,
      overview: "A direct balm to the heart: did We not expand for you your breast, remove your heavy burden, and elevate your mention?",
      keyTakeaway: "For indeed, with hardship [will be] ease. Indeed, with hardship [will be] ease.",
    },
  },
  {
    id: "95",
    number: 95,
    name: "At-Tin",
    arabic: "التين",
    meaning: "The Fig",
    verses: 8,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 28,
    intro: {
      theme: "Human Dignity in Best Stature",
      verseCount: 8,
      overview: "Swears by the Fig, Olive, Mount Sinai, and the secure city of Mecca, affirming that humans were molded in the best possible stature.",
      keyTakeaway: "We have certainly created man in the best of stature.",
    },
  },
  {
    id: "96",
    number: 96,
    name: "Al-'Alaq",
    arabic: "العلق",
    meaning: "The Clinging Clot / Read!",
    verses: 19,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 1,
    intro: {
      theme: "The First Five Verses: Read in the Name of Your Lord",
      verseCount: 19,
      overview: "The historic dawn of Quranic revelation in the Cave of Hira: Angel Jibril embracing the Prophet and commanding him to read with the pen.",
      keyTakeaway: "Recite in the name of your Lord who created—created man from a clinging clot. Recite, and your Lord is the most Generous.",
    },
  },
  {
    id: "97",
    number: 97,
    name: "Al-Qadr",
    arabic: "القدر",
    meaning: "The Night of Decree",
    verses: 5,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 25,
    intro: {
      theme: "The Night Better Than a Thousand Months",
      verseCount: 5,
      overview: "Commemorates Laylat al-Qadr when the Quran descended, filled with peace and angels descending until the emergence of dawn.",
      keyTakeaway: "The Night of Decree is better than a thousand months. The angels and the Spirit descend therein by permission of their Lord.",
    },
  },
  {
    id: "98",
    number: 98,
    name: "Al-Bayyinah",
    arabic: "البينة",
    meaning: "The Clear Proof",
    verses: 8,
    time: "1 min",
    revelation: "Medinan",
    revelationOrder: 100,
    intro: {
      theme: "Sincerity in Religion and the Best of Creation",
      verseCount: 8,
      overview: "Proclaims that religion in its purest essence is nothing other than sincere worship of Allah alone, establishing prayer, and giving zakah.",
      keyTakeaway: "And they were not commanded except to worship Allah, [being] sincere to Him in religion, inclining to truth.",
    },
  },
  {
    id: "99",
    number: 99,
    name: "Az-Zalzalah",
    arabic: "الزلزلة",
    meaning: "The Quake",
    verses: 8,
    time: "1 min",
    revelation: "Medinan",
    revelationOrder: 93,
    intro: {
      theme: "The Earth Disclosing Her Burdens",
      verseCount: 8,
      overview: "Describes the earth convulsing with its final tremor and yielding its records, where an atom's weight of good or evil is seen.",
      keyTakeaway: "So whoever does an atom's weight of good will see it, and whoever does an atom's weight of evil will see it.",
    },
  },
  {
    id: "100",
    number: 100,
    name: "Al-'Adiyat",
    arabic: "العاديات",
    meaning: "The Charging Steeds",
    verses: 11,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 14,
    intro: {
      theme: "Charging Warhorses and Human Ungratefulness",
      verseCount: 11,
      overview: "Evokes charging war steeds panting in the morning raid, striking sparks of fire, waking human consciousness to ungratefulness toward their Lord.",
      keyTakeaway: "Indeed, mankind, to his Lord, is ungrateful. And indeed, he is to that a witness.",
    },
  },
  {
    id: "101",
    number: 101,
    name: "Al-Qari'ah",
    arabic: "القارعة",
    meaning: "The Striking Calamity",
    verses: 11,
    time: "2 min",
    revelation: "Meccan",
    revelationOrder: 30,
    intro: {
      theme: "The Striking Hour and the Light/Heavy Scales",
      verseCount: 11,
      overview: "Portrays people like scattered moths and mountains like carded wool, weighing deeds on divine scales of righteousness.",
      keyTakeaway: "So as for he whose scales are heavy [with good deeds], he will be in a pleasant life.",
    },
  },
  {
    id: "102",
    number: 102,
    name: "At-Takathur",
    arabic: "التكاثر",
    meaning: "Rivalry in World Increase",
    verses: 8,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 16,
    intro: {
      theme: "The Illusion of Accumulation Until the Graves",
      verseCount: 8,
      overview: "A potent critique of materialism: competing in piling up wealth and status distracts you until you visit the graves.",
      keyTakeaway: "Competition in [world] increase diverts you until you visit the graveyards.",
    },
  },
  {
    id: "103",
    number: 103,
    name: "Al-'Asr",
    arabic: "العصر",
    meaning: "Time / The Declining Day",
    verses: 3,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 13,
    intro: {
      theme: "The Four Pillars of Escaping Loss",
      verseCount: 3,
      overview: "Imam ash-Shafi'i remarked that if humanity only reflected on this three-verse surah, it would suffice them. All humanity is in loss except those with faith, righteous deeds, truth, and patience.",
      keyTakeaway: "By time, indeed, mankind is in loss, except for those who have believed and done righteous deeds and advised each other to truth and advised each other to patience.",
    },
  },
  {
    id: "104",
    number: 104,
    name: "Al-Humazah",
    arabic: "الهمزة",
    meaning: "The Slanderer",
    verses: 9,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 32,
    intro: {
      theme: "Condemning Gossip, Backbiting, and Wealth Hoarding",
      verseCount: 9,
      overview: "Denounces those who slander behind backs and count wealth thinking it renders them immortal, warning of the Crusher (Al-Hutamah).",
      keyTakeaway: "Woe to every scorner and mocker who collects wealth and continuously counts it.",
    },
  },
  {
    id: "105",
    number: 105,
    name: "Al-Fil",
    arabic: "الفيل",
    meaning: "The Elephant",
    verses: 5,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 19,
    intro: {
      theme: "Protection of the Ka'bah Against Abraha",
      verseCount: 5,
      overview: "Recalls the Year of the Elephant when Abraha's army marched to destroy the Ka'bah, routed by flocks of birds casting baked clay stones.",
      keyTakeaway: "Did He not make their plan into misguidance? And He sent against them birds in flocks.",
    },
  },
  {
    id: "106",
    number: 106,
    name: "Quraysh",
    arabic: "قريش",
    meaning: "Quraysh",
    verses: 4,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 29,
    intro: {
      theme: "Security, Winter/Summer Journeys, and Gratitude",
      verseCount: 4,
      overview: "Urges the Quraysh tribe to worship the Lord of the Ka'bah who secured their trade caravans, fed them against hunger, and made them safe from fear.",
      keyTakeaway: "Let them worship the Lord of this House, who has fed them against hunger and made them safe from fear.",
    },
  },
  {
    id: "107",
    number: 107,
    name: "Al-Ma'un",
    arabic: "الماعون",
    meaning: "Small Kindnesses",
    verses: 7,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 17,
    intro: {
      theme: "Faith Tied to Feeding the Needy and Lending Help",
      verseCount: 7,
      overview: "Defines the true denier of religion not merely as an intellectual skeptic, but as one who pushes away the orphan and withholds small neighborly kindnesses.",
      keyTakeaway: "So woe to those who pray [but] who are heedless of their prayer—those who make a show [of their deeds] and withhold simple assistance.",
    },
  },
  {
    id: "108",
    number: 108,
    name: "Al-Kawthar",
    arabic: "الكوثر",
    meaning: "The Abundance",
    verses: 3,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 15,
    intro: {
      theme: "Abundant Favor and the Heavenly River",
      verseCount: 3,
      overview: "The shortest surah in the Quran, consoling the Prophet ﷺ upon the death of his sons: promising him Al-Kawthar (the heavenly river of abundance).",
      keyTakeaway: "Indeed, We have granted you, [O Muhammad], al-Kawthar. So pray to your Lord and sacrifice.",
    },
  },
  {
    id: "109",
    number: 109,
    name: "Al-Kafirun",
    arabic: "الكافرون",
    meaning: "The Disbelievers",
    verses: 6,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 18,
    intro: {
      theme: "Uncompromising Integrity of Worship",
      verseCount: 6,
      overview: "Revealed when pagan leaders proposed a compromise to trade worshipping each other's gods year-by-year, establishing pure monotheistic boundary.",
      keyTakeaway: "Say, 'O disbelievers, I do not worship what you worship... For you is your religion, and for me is my religion.'",
    },
  },
  {
    id: "110",
    number: 110,
    name: "An-Nasr",
    arabic: "النصر",
    meaning: "The Divine Support",
    verses: 3,
    time: "1 min",
    revelation: "Medinan",
    revelationOrder: 114,
    intro: {
      theme: "The Conquest of Mecca and Glorification",
      verseCount: 3,
      overview: "The last complete surah revealed, signalling the completion of the prophetic mission with crowds entering Islam, commanding tasbeeh and istighfar.",
      keyTakeaway: "When the victory of Allah has come and the conquest... then exalt with praise of your Lord and ask forgiveness of Him.",
    },
  },
  {
    id: "111",
    number: 111,
    name: "Al-Masad",
    arabic: "المسد",
    meaning: "The Palm Fiber",
    verses: 5,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 6,
    intro: {
      theme: "The Demise of Arrogance and Hostility",
      verseCount: 5,
      overview: "A miraculous prophecy concerning the Prophet's bitter uncle Abu Lahab and his wife who threw thorns in the Prophet's path, dying without faith.",
      keyTakeaway: "Perished are the hands of Abu Lahab, and ruined is he. His wealth will not avail him or that which he gained.",
    },
  },
  {
    id: "112",
    number: 112,
    name: "Al-Ikhlas",
    arabic: "الإخلاص",
    meaning: "The Sincerity of Faith",
    verses: 4,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 22,
    intro: {
      theme: "Absolute Monotheism (Tawhid)",
      verseCount: 4,
      overview: "Equal to one-third of the Quran in reward, defining the absolute oneness, eternity, and uniqueness of Allah who neither begets nor is born.",
      keyTakeaway: "Say, 'He is Allah, [who is] One, Allah, the Eternal Refuge. He neither begets nor is born, nor is there to Him any equivalent.'",
    },
  },
  {
    id: "113",
    number: 113,
    name: "Al-Falaq",
    arabic: "الفلق",
    meaning: "The Daybreak",
    verses: 5,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 20,
    intro: {
      theme: "Refuge from External Evils and Envy",
      verseCount: 5,
      overview: "The first of the two protective chapters (Al-Mu'awwidhatayn), seeking sanctuary with the Lord of daybreak from darkness, witchcraft, and the envious.",
      keyTakeaway: "Say, 'I seek refuge in the Lord of daybreak from the evil of that which He created... and from the evil of an envier when he envies.'",
    },
  },
  {
    id: "114",
    number: 114,
    name: "An-Nas",
    arabic: "الناس",
    meaning: "Mankind",
    verses: 6,
    time: "1 min",
    revelation: "Meccan",
    revelationOrder: 21,
    intro: {
      theme: "Refuge from Internal Whispers and Doubts",
      verseCount: 6,
      overview: "The final seal of the Holy Quran, seeking refuge in the Lord, King, and God of mankind from the retreating whisperer who whispers doubts into human chests.",
      keyTakeaway: "Say, 'I seek refuge in the Lord of mankind, the Sovereign of mankind, the God of mankind, from the evil of the retreating whisperer.'",
    },
  },
];
